version: '3.8'  # Add this for compatibility

services:
  postgres:
    image: postgres:18  # Specific version for stability
    container_name: postgres
    restart: always  # Auto-restart on failure
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: